export const defaultTable = {  
    a: "AAAAA",
    b: "AAAAB",
    c: "AAABA",
    d: "AAABB",
    e: "AABAA",
    f: "AABAB",
    g: "AABBA",
    h: "AABBB",
    i: "ABAAA",
    j: "ABAAB",
    k: "ABABA",
    l: "ABABB",
    m: "ABBAA",
    n: "ABBAB",
    o: "ABBBA",
    p: "ABBBB",
    q: "BAAAA",
    r: "BAAAB",
    s: "BAABA",
    t: "BAABB",
    u: "BABAA",
    v: "BABAB",
    w: "BABBA",
    x: "BABBB",
    y: "BBAAA",
    z: "BBAAB"
  }
  
  export const alternativeTable = {  
    a: "BBBBB",
    b: "BBBBA",
    c: "BBBAB",
    d: "BBBAA",
    e: "BBAAA",
    f: "BBAAB",
    g: "BBABA",
    h: "BBABB",
    i: "BABBB",
    j: "BABBA",
    k: "BABAB",
    l: "BABAA",
    m: "BAABB",
    n: "BAABA",
    o: "BAAAB",
    p: "BAAAA",
    q: "ABBBB",
    r: "ABBBA",
    s: "ABBAB",
    t: "ABBAA",
    u: "ABAAA",
    v: "ABAAB",
    w: "ABABA",
    x: "ABABB",
    y: "AABBB",
    z: "AABBA"
  }