export const defaultTable = {  
    a: "AAAAA",
    b: "AAAAB",
    c: "AAABA",
    d: "AAABB",
    e: "AABAA",
    f: "AABAB",
    g: "AABBA",
    h: "AABBB",
    i: "ABAAA",
    j: "ABAAB",
    k: "ABABA",
    l: "ABABB",
    m: "ABBAA",
    n: "ABBAB",
    o: "ABBBA",
    p: "ABBBB",
    q: "BAAAA",
    r: "BAAAB",
    s: "BAABA",
    t: "BAABB",
    u: "BABAA",
    v: "BABAB",
    w: "BABBA",
    x: "BABBB",
    y: "BBAAA",
    z: "BBAAB"
  }
  
  export const alternativeTable = {  
    a: "BBBBB",
    b: "BBBBA",
    c: "BBBAB",
    d: "BBBAA",
    e: "BBAAA",
    f: "BBAAB",
    g: "BBABA",
    h: "BBABB",
    i: "BABBB",
    j: "BABBA",
    k: "BABAB",
    l: "BABAA",
    m: "BAABB",
    n: "BAABA",
    o: "BAAAB",
    p: "BAAAA",
    q: "ABBBB",
    r: "ABBBA",
    s: "ABBAB",
    t: "ABBAA",
    u: "ABAAA",
    v: "ABAAB",
    w: "ABABA",
    x: "ABABB",
    y: "AABBB",
    z: "AABBA"
  }

  export const defaultIJUVTable = {  
    a: "AAAAA",
    b: "AAAAB",
    c: "AAABA",
    d: "AAABB",
    e: "AABAA",
    f: "AABAB",
    g: "AABBA",
    h: "AABBB",
    i: "ABAAA",
    j: "ABAAA",
    k: "ABAAB",
    l: "ABABA",
    m: "ABABB",
    n: "ABBAA",
    o: "ABBAB",
    p: "ABBBA",
    q: "ABBBB",
    r: "BAAAA",
    s: "BAAAB",
    t: "BAABA",
    u: "BAABB",
    v: "BAABB",
    w: "BABAA",
    x: "BABAB",
    y: "BABBA",
    z: "BABBB",
  }
  export const alternativeIJUVTable = {  
    a: "BBBBB",
    b: "BBBBA",
    c: "BBBAB",
    d: "BBBAA",
    e: "BBABB",
    f: "BBABA",
    g: "BBAAB",
    h: "BBAAA",
    i: "BABBB",
    j: "BABBB",
    k: "BABBA",
    l: "BABAB",
    m: "BABAA",
    n: "BAABB",
    o: "BAABA",
    p: "BAAAB",
    q: "BAAAA",
    r: "ABBBB",
    s: "ABBBA",
    t: "ABBAB",
    u: "ABBAA",
    v: "ABBAA",
    w: "ABABB",
    x: "ABABA",
    y: "ABAAB",
    z: "ABAAA"
  }

